package lotto

enum class LottoGameState {
    INITIALIZED,
    PURCHASING,
    PURCHASING_REQUESTED,
    PURCHASING_RESPONDED,
    PURCHASING_FINISHED,
    DRAWING,
    DRAWING_REQUESTED,
    DRAWING_RESPONDED,
    DRAWING_FINISHED,
    WINNING,
    FINISHED,
    ERROR
}