package lotto.model

import FIFTH_REWARD
import FIRST_REWARD
import FOURTH_REWARD
import LOTTO_FIFTH_RANK_MESSAGE
import LOTTO_FIRST_RANK_MESSAGE
import LOTTO_FOURTH_RANK_MESSAGE
import LOTTO_SECOND_RANK_MESSAGE
import LOTTO_THIRD_RANK_MESSAGE
import MATCH_FIVE
import MATCH_FOUR
import MATCH_SIX
import MATCH_THREE
import SECOND_REWARD
import THIRD_REWARD

enum class LottoResult(val message: String, val prize: Int, val count: Int) {
    FIRST(LOTTO_FIRST_RANK_MESSAGE, FIRST_REWARD, MATCH_SIX),
    SECOND(LOTTO_SECOND_RANK_MESSAGE, SECOND_REWARD, MATCH_SIX),
    THIRD(LOTTO_THIRD_RANK_MESSAGE, THIRD_REWARD, MATCH_FIVE),
    FOURTH(LOTTO_FOURTH_RANK_MESSAGE, FOURTH_REWARD, MATCH_FOUR),
    FIFTH(LOTTO_FIFTH_RANK_MESSAGE, FIFTH_REWARD, MATCH_THREE)
}