package lotto.model

import FIFTH_REWARD
import FIRST_REWARD
import FOURTH_REWARD
import LOTTO_FIFTH_RANK_MESSAGE
import LOTTO_FIRST_RANK_MESSAGE
import LOTTO_FOURTH_RANK_MESSAGE
import LOTTO_SECOND_RANK_MESSAGE
import LOTTO_THIRD_RANK_MESSAGE
import SECOND_REWARD
import THIRD_REWARD
import ZERO

enum class LottoResult(val message: String, val prize: Int, val count: Int) {
    FIRST(LOTTO_FIRST_RANK_MESSAGE, FIRST_REWARD, ZERO),
    SECOND(LOTTO_SECOND_RANK_MESSAGE, SECOND_REWARD, ZERO),
    THIRD(LOTTO_THIRD_RANK_MESSAGE, THIRD_REWARD, ZERO),
    FOURTH(LOTTO_FOURTH_RANK_MESSAGE, FOURTH_REWARD, ZERO),
    FIFTH(LOTTO_FIFTH_RANK_MESSAGE, FIFTH_REWARD, ZERO)
}